### ISSUE TITLE
Getting all english words

### ISSUE THREAD

**Issue by timothyckl** [meetDeveloper/freeDictionaryAPI#112]
Is there a way to retrieve all English words with the API?

**Comment by AndrewDiMola** [comment]
Looks like there was a Wiktionary migration in 2022. 

@timothyckl, @AmjadHD - Curious if either of you know of a lead for a new list of supported words?

Related: https://github.com/meetDeveloper/freeDictionaryAPI/issues/102#issuecomment-1975838441
