### ISSUE TITLE
SSL Certificate Expired

### ISSUE THREAD

**Issue by rpungin** [meetDeveloper/freeDictionaryAPI#119]
Looks like https://api.dictionaryapi.dev/ SSL certificate has expired.

<img width="642" alt="Screen Shot 2021-12-09 at 12 47 58 AM" src="https://user-images.githubusercontent.com/3802522/145341572-627c0e34-6797-4a29-aa1c-a40e2da9257b.png">

**Comment by cloudy-sfu** [comment]
The same problem. @meetDeveloper

**Comment by meetDeveloper** [comment]
Sorry for the inconvenience certbot did not automatically renewed it, I am having problem connecting to the instance will try to fix this ASAP.

**Comment by meetDeveloper** [comment]
This should be fixed now, sorry for the inconvenience. I will look into why certbot is not renewing it automatically.

**Comment by cloudy-sfu** [comment]
It is fixed, thank you very much!

**Comment by sajadhsm** [comment]
@meetDeveloper It looks like the certificate needs to be renewed again.

![image](https://user-images.githubusercontent.com/20022818/157387497-c149b19d-635b-4de3-9d64-8827363f0411.png)

**Comment by meetDeveloper** [comment]
@sajadhsm Renewed.
