### ISSUE TITLE
Currently down

### ISSUE THREAD

**Issue by joabarzua** [meetDeveloper/freeDictionaryAPI#148]
Being returned:
{"title":"Something Went Wrong","message":"Sorry pal, something went wrong, and its not your fault.","resolution":"You can try the search again at later time or head to the web instead."}

**Comment by leifadev** [comment]
What request did you put in URL?

**Comment by nityanand86876** [comment]
i also came across the same error on go to http://localhost:3000/api/v1/entries/en/apple/
this api is not showing a single word but throughs the same error that @joabarzua got

**Comment by lsnnt** [comment]
i have resolved the issue by doing what is told in #111 dochange the `fc` and `fcv` and `async` and retry
