### ISSUE TITLE
Expired Certificate

### ISSUE THREAD

**Issue by wardellbagby** [meetDeveloper/freeDictionaryAPI#167]
As of December 3rd, 2022 7:52 PT, the Let's Encrypt SSL certificate has expired for https://api.dictionaryapi.dev/

Attempting to invoke the API will result in a certificate expiration issue, as seen below:

https://api.dictionaryapi.dev/api/v2/entries/en/gust
<img width="835" alt="Screen Shot 2022-12-03 at 7 53 32 PM" src="https://user-images.githubusercontent.com/7834478/205473474-8d693927-c9ea-4745-abad-079dac82a64a.png">
<img width="835" alt="Screen Shot 2022-12-03 at 7 53 25 PM" src="https://user-images.githubusercontent.com/7834478/205473480-33fc860b-13ae-4720-9a6a-ce3175b1ac8e.png">

**Comment by iLLHunter** [comment]
I am experiencing this as well. I will check back tomorrow to see if the renewal script has run, but wanted to leave a comment here

**Comment by wardellbagby** [comment]
Looks like it renewed and is now working!
