### ISSUE TITLE
API is down (Jan/2/2023)

### ISSUE THREAD

**Issue by HinTran013** [meetDeveloper/freeDictionaryAPI#172]
Maybe this API is down today (Jan/2/2023). I can't make any GET requests, also the search bar on the official API website doesn't work. Does anyone have the same problem?

**Comment by sdip15fa** [comment]
Same here

**Comment by ehtashamparity** [comment]
Facing Same Issue

**Comment by adarshjambhulkar** [comment]
same here

**Comment by sdip15fa** [comment]
@meetDeveloper

**Comment by M-NabeelAli** [comment]
fixed...

https://github.com/meetDeveloper/freeDictionaryAPI/issues/174

**Comment by HinTran013** [comment]
The issue is fixed. Thank you, everyone
