### ISSUE TITLE
API is not responding

### ISSUE THREAD

**Issue by M-NabeelAli** [meetDeveloper/freeDictionaryAPI#174]
can't make any requests,  API is not working.

![image](https://user-images.githubusercontent.com/49489233/210202928-4c167d54-365f-4a30-8cc0-ebf410c664e6.png)

**Comment by sdip15fa** [comment]
Duplicate of #172

**Comment by M-NabeelAli** [comment]
issues resolved


![image](https://user-images.githubusercontent.com/49489233/210211427-96fe5199-5d21-4d4a-8540-68a30b1f163b.png)
