### ISSUE TITLE
Server Down

### ISSUE THREAD

**Issue by Mohit-k-Mummon** [meetDeveloper/freeDictionaryAPI#175]
Was using the api in a react project when all of a sudden started recieving cors error. Could be i send too many requests, but even the search function on the webpage is down currently.

**Comment by pavlo-myskov** [comment]
Same stuff. Access to fetch at ... from origin ... has been blocked by CORS policy

**Comment by M-NabeelAli** [comment]
API is DOWN
![image](https://user-images.githubusercontent.com/49489233/214770820-35554048-4b5d-4352-b415-ef49f1fa6591.png)

**Comment by nathanielfischer** [comment]
Same. Doesn't work for me.

**Comment by M-NabeelAli** [comment]
It's working now
