### ISSUE TITLE
Server is down again :(

### ISSUE THREAD

**Issue by sohagdev** [meetDeveloper/freeDictionaryAPI#178]

**Comment by Amirsa025** [comment]
i can not get api from site 
error internal error 500

**Comment by joshua-matchala** [comment]
Same here.

**Comment by joshua-matchala** [comment]
@meetDeveloper

**Comment by Sirojiddin96** [comment]
Will Someone fix issue?

**Comment by rutikwankhade** [comment]
What re the rate limits for this API?

**Comment by hidalest** [comment]
I'm having the same issue, error 500

**Comment by rutikwankhade** [comment]
the API is not working. i almost finished my app and its not working. Are there any other alternatives like these?

**Comment by ninadsutrave** [comment]
@sohagdev @amirsa025 @joshua-matchala @hidalest @rutikwankhade @Sirojiddin96 do you guys by any chance find any free alternative to the meanings API? Preferably one that provides word pronunciation as well? 
Do let me know n thanks in advance!
