### ISSUE TITLE
API not working

### ISSUE THREAD

**Issue by rutikwankhade** [meetDeveloper/freeDictionaryAPI#179]
the API is not working - 4th Feb 2023. even the search bar on the website is not working

**Comment by danulqua** [comment]
Yep, I've also wanted to work with this API. Would love to know if it works again.

**Comment by rutikwankhade** [comment]
hey, @meetDeveloper Thank you so much for building this. we are grateful. How much does it cost for you to run the API every month?  If it is not feasible, you can add a cheap pro plan like a dollar a month, so it never goes down. 🙌
