### ISSUE TITLE
Server is down :(((

### ISSUE THREAD

**Issue by nedaashkan** [meetDeveloper/freeDictionaryAPI#180]
hi , Server is down :((( I can not  get any data...

**Comment by cweibel73** [comment]
I was ready to debug my Wordle/Randomle game until I figured out it was the API. Glad I checked!

**Comment by AbbyNyakara** [comment]
I thought its my internet...

**Comment by meetDeveloper** [comment]
dictionaryapi.dev domain got expired, I have renewed it now. Really sorry for the inconvenience caused.
