### ISSUE TITLE
[Server down] The audio server is down

### ISSUE THREAD

**Issue by bi1101** [meetDeveloper/freeDictionaryAPI#205]
Hi, thanks a lot for the project! It's a really wonderful piece of engineering!

I noticed the audio server was down.

Link: https://api.dictionaryapi.dev/media/pronunciations/en/hello-au.mp3

**Comment by AnthonyChablov** [comment]
Yes currently facing the same issue and hope it will be resolved soon

**Comment by meetDeveloper** [comment]
This has been resolved now. Thanks for using this API.
