### ISSUE TITLE
Audio Not Working

### ISSUE THREAD

**Issue by adilcodes** [meetDeveloper/freeDictionaryAPI#206]
I've been working with this API lately, it's really amazing and easy to use but the audio is not working 🥺 Please fix this!!! I've made the complete HTML structure and done with the JS part as well. I don't want to change the API resource. Kindly fix it asap!!!

Thank a lot :)
Adil Sheikh.

**Comment by meetDeveloper** [comment]
This has been resolved now.

**Comment by adilcodes** [comment]
Thank you very much 😊
