### ISSUE TITLE
Audio file not working

### ISSUE THREAD

**Issue by georgee04** [meetDeveloper/freeDictionaryAPI#207]
Hi there, I have been a fan of your freeDictionaryAPI tool which has been very helpful and I have utilised it in my University project however there has been an issue recently I would like your assistance on if possible. In the JSON data for a word there sometimes may be a link to an audio file of the pronunciation of that word such as for the word “string" we’d receive: 

https://api.dictionaryapi.dev/media/pronunciations/en/string-us.mp3

However, none of these links seems to be working anymore and it is hindering my project. I have asked a few of my friends to see if the error is on my end but they seem to be having the same issues with Google saying it is the https://dictionaryapi.dev/ server’s fault. Would it be possible to take a look into this, any assistance would be appreciated.

Thank you.

**Comment by meetDeveloper** [comment]
This has been resolved now.
