### ISSUE TITLE
Audio Playback Not Working

### ISSUE THREAD

**Issue by mohamedhesham221** [meetDeveloper/freeDictionaryAPI#210]
Description:
I encountered an issue with audio playback while using the Dictionary API. When attempting to play audio pronunciations for word definitions, I received the following error message: "Uncaught (in promise) DOMException: Failed to load because no supported source was found."

Expected Behavior:
The audio pronunciation should play successfully when clicked.

Actual Behavior:
An error message is displayed, indicating that the audio file failed to load.

**Comment by meetDeveloper** [comment]
This has been resolved now.
