### ISSUE TITLE
No audio

### ISSUE THREAD

**Issue by billie-spektor** [meetDeveloper/freeDictionaryAPI#215]
Thanks for creating this API!

The audio doesn't work for me. For instance, when calling https://api.dictionaryapi.dev/api/v2/entries/en/hello, i get the following audio URL that does not work: 

https://api.dictionaryapi.dev/media/pronunciations/en/hello-au.mp3

**Comment by tak0m0** [comment]
True.

**Comment by NuraSad** [comment]
Have the same issue. The audio link from API shows a blank page.

**Comment by billie-spektor** [comment]
The issue disappeared, so I will close this 👍
