### ISSUE TITLE
Error code 526: Invalid SSL certificate

### ISSUE THREAD

**Issue by baogiadinh1003** [meetDeveloper/freeDictionaryAPI#216]
Currently api got error 526 when using, please recheck 

![image](https://github.com/user-attachments/assets/743e2627-4164-4e19-9b96-ce82738b89ba)

**Comment by AntsForBreakfast** [comment]
Same

**Comment by paypay-komi** [comment]
same

**Comment by IzhanAli** [comment]
@meetDeveloper

**Comment by sendtodilanka** [comment]
same issue

**Comment by SamChoi-94** [comment]
Same

**Comment by meetDeveloper** [comment]
This should be fixed now. Sorry for the inconvenience.  Thank you for using this API
