### ISSUE TITLE
Any plans to add more languages?

### ISSUE THREAD

**Issue by nmapx** [meetDeveloper/freeDictionaryAPI#70]
Hi there! First of all - great job with the project. I wanted to ask if there are any plans to add more languages especially Polish? I would really like to use it in my project. Keep up the good work!

**Comment by meetDeveloper** [comment]
Yeah, I will add more language as soon as the sources I use to find definitions add more languages, last time I checked polish was missing from there, I will recheck and add it if possible. Thanks for using this API, also sorry for late reply work life balance does not let me actively work on the API, however currently I am fixing many issues right now and making it much more stable. :)
