### ISSUE TITLE
Rate limit

### ISSUE THREAD

**Issue by traderjosh** [meetDeveloper/freeDictionaryAPI#78]
Is a 429 status code returned for reaching the rate limit?

If in my app, I'm making the client call your api, the rate limit belongs to him right? So 50 people using the app at the same time calling the API won't cause my rate limit to expand... you understand? The scenario is a game where the client on the frontend is making the fetch calls. I'm wondering about reaching the rate limit if many people are playing on the same time.

**Comment by Etiene** [comment]
Have you considered saving the call result into your own db every time someone fetches it? That way you only call the api once if you don't have the definition yet.

**Comment by meetDeveloper** [comment]
@Etiene Yeah, I have considered it, I will shortly do that.

**Comment by TychoTheTaco** [comment]
I keep getting a 429 error also, even though I'm only sending a few requests per day. Unfortunately caching these wont help for me because most of the requests are different.

**Comment by usbader** [comment]
@meetDeveloper what's the rate limit?

**Comment by meetDeveloper** [comment]
This should be fixed now. I have to change architecture a little to scale the API to handle millions request per month. And my resources are limited as this now takes lots of expenditure to operate.
