### ISSUE TITLE
I am unable to pay for the API expenses. Please help this API keep running.

### ISSUE THREAD

**Issue by meetDeveloper** [meetDeveloper/freeDictionaryAPI#83]
The number of requests to this API has been growing rapidly and it is becoming increasingly difficult for me to fund this API single-hand.

Kindly please donate so that I am able to fund the API. 

[![paypal](https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif)](https://www.paypal.me/paytosuraj)

**Comment by Semionbatkhan** [comment]
Hi meetDeveloper, please write down you mail here, for me to contact you directly or you can send an email to djekson603@gmail.com. I have a proposition you might have interested in. We can help you with the expenses. We have an English school online and we need this Dictionary API.

**Comment by huntit** [comment]
Perhaps people could pay to help remove the rate limit, or to access the code for API v2 ?

**Comment by meetDeveloper** [comment]
I  have updated the code. @huntit
