### ISSUE TITLE
The README has API v2 format, but the code here is for API v1.

### ISSUE THREAD

**Issue by huntit** [meetDeveloper/freeDictionaryAPI#84]
The README has API v2 format, but the code here is for API v1.

Do you have the code for API v2 format, that you could post here ?

**Comment by tomasen** [comment]
The code doesn't seem to be the latest copy. A little more transparency here would be great.

**Comment by meetDeveloper** [comment]
@huntit @tomasen @ngocsangyem @kyfk @pdarc @TheBotlyNoob I have updated the code.
