### ISSUE TITLE
API is down. SSL error 

### ISSUE THREAD

**Issue by sooswastaken** [meetDeveloper/freeDictionaryAPI#89]
Cannot connect to host api.dictionaryapi.dev:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1123)')]

Is this on my end or whole API?

**Comment by rpungin** [comment]
Looks like the whole API. The query from the website does not work either:
https://api.dictionaryapi.dev/api/v2/entries/en_US/test

![Screen Shot 2021-06-11 at 11 11 42 PM](https://user-images.githubusercontent.com/3802522/121763480-74864480-cb0a-11eb-9d5b-e7baa69d67f8.png)

**Comment by solamour** [comment]
Looks like the certificate expired... today.

![image](https://user-images.githubusercontent.com/330249/121763590-22392980-caf2-11eb-8de4-8d2d27cb3c64.png)

**Comment by sooswastaken** [comment]
It works now, I think the owner renewed the certificate.
