### ISSUE TITLE
Some of the words are not recognised anymore

### ISSUE THREAD

**Issue by queleok** [meetDeveloper/freeDictionaryAPI#96]
E.g. querying `bee`, `bees`, `lates` yields:
```
{"title":"No Definitions Found","message":"Sorry pal, we couldn't find definitions for the word you were looking for.","resolution":"You can try the search again at later time or head to the web instead."}
```
while querying `all` yields:
```
{"title":"Something Went Wrong","message":"Sorry pal, something went wrong, and its not your fault.","resolution":"You can try the search again at later time or head to the web instead."}
```
I'm sure those used to work before.

**Comment by meetDeveloper** [comment]
I have fixed the results when queries `all`. I will soon look into other queries which are returning 404.

**Comment by methusaleh** [comment]
The same happens for basic words like "apple".
@queleok @meetDeveloper

**Comment by meetDeveloper** [comment]
@queleok @methusaleh I have fixed this. @queleok The word `lates` will still lead to no definitions found as this word is not present in the source I refer to, rest all I have fixed.

**Comment by queleok** [comment]
Fantastic, thank you, @meetDeveloper

**Comment by meetDeveloper** [comment]
@queleok @methusaleh Also can you guys look into this https://github.com/meetDeveloper/freeDictionaryAPI/issues/102

**Comment by hueychen27** [comment]
The word `is` too.
