### ISSUE TITLE
Breaking changes in API v1

### ISSUE THREAD

**Issue by Gidoont** [meetDeveloper/freeDictionaryAPI#97]
I've just discovered the API has been changed suddenly. I'm using API v1. My project that uses the API stopped working properly so I checked the response and found it does not have the same data structure as before. Pretty sure the changes happened just recently.

**Comment by Gidoont** [comment]
To be more specific, forms of speech inside "meaning" were arrays containing objects with definition and example: 

```json
"meaning": {
  "noun": [ 
    { "definition": "...", "example": "..."} 
   ]
}
```

Right now they are objects containing "definitions" property, that contains an array with definition, example, synonyms, antonyms.

```json
"meaning": {
  "noun": { 
   "definitions": [ 
     { "definition": "...", "example": "...", "synonyms": "...", "antonyms": "..." } 
    ] 
  }
}
```

Also, the value of property "phonetic" always had slashes on both sides. 
Now there are no slashes: `/wəːk/` -> `wəːk`

**Comment by meetDeveloper** [comment]
Will look into this.

**Comment by meetDeveloper** [comment]
This is fixed now.

**Comment by meetDeveloper** [comment]
@Gidoont Yeah phonetic bit has been changed, will it be possible to make changes at your end for this?

**Comment by Gidoont** [comment]
Yes, no problem. Thanks for addressing it.

**Comment by meetDeveloper** [comment]
@Gidoont Also can you guys look into this #102 This will help me a lot.
